import { publicService } from './services.js';
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'}});
const https=value=>{try{return new URL(value).protocol==='https:'}catch{return false}};
async function boundedJson(request){const declared=Number(request.headers.get('content-length')||0);if(declared>8192)return{response:json({error:'request_too_large'},413)};const text=await request.text();if(text.length>8192)return{response:json({error:'request_too_large'},413)};try{return{value:JSON.parse(text)}}catch{return{response:json({error:'invalid_json'},400)}}}
export async function authenticateReviewer(request,env){const authorization=request.headers.get('authorization')||'';if(!env.IDENTITY||!env.REVIEWS_DB||!authorization.startsWith('Bearer '))return{response:json({error:'reviewer_unauthorized'},401)};const identity=await env.IDENTITY.fetch(new Request('https://brasa-identity/api/government/operator/introspect',{headers:{authorization}}));if(!identity.ok)return{response:json({error:'reviewer_unauthorized'},401)};const profile=await identity.json(),reviewer=await env.REVIEWS_DB.prepare("SELECT display_id AS displayId,name,role FROM government_reviewers WHERE display_id=? AND status='active'").bind(profile.display_id).first();return reviewer?{reviewer}:{response:json({error:'reviewer_unauthorized'},401)}}
export async function applyReviews(services,env){if(!env.REVIEWS_DB||!services.length)return services;const placeholders=services.map(()=>'?').join(','),result=await env.REVIEWS_DB.prepare(`SELECT service_id AS serviceId,source_url AS sourceUrl,evidence_url AS evidenceUrl,reviewed_at AS reviewedAt,expires_at AS reviewExpiresAt FROM source_reviews WHERE service_id IN (${placeholders}) AND status='reviewed' AND expires_at>datetime('now')`).bind(...services.map(item=>item.id)).all();const reviews=new Map(result.results.map(item=>[item.serviceId,item]));return services.map(service=>{const review=reviews.get(service.id);return review&&review.sourceUrl===service.sourceUrl?{...service,sourceStatus:'reviewed',reviewedAt:review.reviewedAt,reviewExpiresAt:review.reviewExpiresAt,evidenceUrl:review.evidenceUrl}:service})}
export async function listReviews(request,env){const status=new URL(request.url).searchParams.get('status')||'reviewed';if(!['reviewed','suspended','expired'].includes(status))return json({error:'invalid_status'},400);const result=await env.REVIEWS_DB.prepare('SELECT service_id AS serviceId,source_url AS sourceUrl,evidence_url AS evidenceUrl,status,reviewer_display_id AS reviewerDisplayId,reviewed_at AS reviewedAt,expires_at AS expiresAt,updated_at AS updatedAt FROM source_reviews WHERE status=? ORDER BY updated_at DESC LIMIT 100').bind(status).all();return json({data:result.results,meta:{status,limit:100}})}
export async function reviewSource(request,env,serviceId,records,reviewer){
  if(!/^[a-z0-9-]{1,120}$/.test(serviceId))return json({error:'invalid_service_id'},400);
  const service=records.map(publicService).find(item=>item.id===serviceId);if(!service)return json({error:'service_not_found'},404);
  const parsed=await boundedJson(request);if(parsed.response)return parsed.response;const input=parsed.value||{},allowed=new Set(['sourceUrl','evidenceUrl','expiresAt','reason','approvals']),approvalKeys=['sourceOwnership','currentRequirements','evidence','expiry','responsibleReviewer'];
  if(Object.keys(input).some(key=>!allowed.has(key))||!input.approvals||Object.keys(input.approvals).length!==approvalKeys.length||!approvalKeys.every(key=>input.approvals[key]===true)||input.sourceUrl!==service.sourceUrl||!https(input.sourceUrl)||!https(input.evidenceUrl)||typeof input.reason!=='string'||input.reason.trim().length<3||input.reason.length>500)return json({error:'invalid_source_review'},400);
  const expiry=Date.parse(input.expiresAt||'');if(!Number.isFinite(expiry)||expiry<=Date.now()||expiry>Date.now()+366*86400000)return json({error:'invalid_review_expiry'},400);
  const now=new Date().toISOString(),expiresAt=new Date(expiry).toISOString();
  await env.REVIEWS_DB.batch([
    env.REVIEWS_DB.prepare("INSERT INTO source_reviews(service_id,source_url,evidence_url,status,reviewer_display_id,reviewed_at,expires_at,updated_at) VALUES (?,?,?,'reviewed',?,?,?,?) ON CONFLICT(service_id) DO UPDATE SET source_url=excluded.source_url,evidence_url=excluded.evidence_url,status='reviewed',reviewer_display_id=excluded.reviewer_display_id,reviewed_at=excluded.reviewed_at,expires_at=excluded.expires_at,updated_at=excluded.updated_at").bind(service.id,service.sourceUrl,input.evidenceUrl,reviewer.displayId,now,expiresAt,now),
    env.REVIEWS_DB.prepare("INSERT INTO source_review_audit(id,service_id,action,actor_display_id,reason,evidence_url) VALUES (?,?,'review',?,?,?)").bind(crypto.randomUUID(),service.id,reviewer.displayId,input.reason.trim(),input.evidenceUrl)
  ]);
  return json({data:{serviceId:service.id,sourceUrl:service.sourceUrl,sourceStatus:'reviewed',reviewedAt:now,reviewExpiresAt:expiresAt,evidenceUrl:input.evidenceUrl}});
}
